site_name: ckanext-collection
site_url: https://datashades.github.io/ckanext-collection/

repo_url:  https://github.com/DataShades/ckanext-collection

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: ["ckanext"]
          options:
            show_root_full_path: false
            show_root_toc_entry: false
            show_symbol_type_heading: true
            show_source: false
            docstring_section_style: spacy
  - search:
      separator: '[\s\-\.\_]+'

watch:
  - README.md
  - ckanext/collection/utils

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    # Palette toggle for light mode
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate

nav:
  - index.md
  - installation.md
  - usage.md
  - interfaces.md
  - Structure:
    - structure/index.md
    - structure/collection.md
    - structure/domain.md
    - structure/data.md
    - structure/pager.md
    - structure/columns.md
    - structure/serializer.md
    - structure/filters.md
  - Examples:
    - examples/index.md
  - configuration.md
  - integrations.md
