version: 1
groups:
  - annotation: ckanext-collection
    options:
      - key: ckanext.collection.auth.anonymous_collections
        type: list
        editable: true
        description: |
          Names of registered collections that are viewable by any visitor,
          including anonymous.

      - key: ckanext.collection.auth.authenticated_collections
        type: list
        editable: true
        description: |
          Names of registered collections that are viewable by any
          authenticated user.

      - key: ckanext.collection.include_htmx_asset
        type: bool
        description: |
          Add HTMX asset to pages. Enable this option if you are using CKAN
          v2.10

      - key: ckanext.collection.htmx_init_modules
        type: bool
        description: |
          Initialize CKAN JS modules every time HTMX fetches HTML from the
          server.

      - key: ckanext.collection.export.csv.serializer
        default: ckanext.collection.utils.serialize:CsvSerializer
        description: |
          Import path for serializer used by CSV export endpoint.

      - key: ckanext.collection.export.json.serializer
        default: ckanext.collection.utils.serialize:JsonSerializer
        description: |
          Import path for serializer used by JSON export endpoint.

      - key: ckanext.collection.export.jsonl.serializer
        default: ckanext.collection.utils.serialize:JsonlSerializer
        description: |
          Import path for serializer used by JSONl export endpoint.

      - key: ckanext.collection.export.<format>.serializer
        type: dynamic
        description: |
          Import path for serializer used by `format`-export endpoint.
